# For more info on HTTP files go to https://aka.ms/vs/httpfile
@baseUrl = https://localhost:44382/api

###
#get Notes for Profile Page
POST {{baseUrl}}/search/searchResources
Authorization: <<Add bearer token here>>
Content-Type: application/json

{ 
    "searchText": "levelName:'Managers' AND operatingOfficeName: 'Boston'", 
    "filterQuery": "availabilityDates/any(a: a/date gt 2023-12-05T00:00:00Z) and languages/any(a: a/name eq 'English')" 
}


###
#get Notes for Profile Page
GET {{baseUrl}}/queryIntentOpenAI/getAzureSearchQueryFromSearchText?searchQuery='managers in boston'
Authorization: <Add Bearer Here>

