using System;

namespace Staffing.Coveo.API.ViewModels
{
    public class CommonSourceViewModel
    {
        public string Source { get; set; }
        public string FirstName { get; set; }
        public string FamiliarFirstName { get; set; }
        public string LastName { get; set; }
        public string FamiliarLastName { get; set; }
        public string EmployeeCode { get; set; }
        public string FullName { get; set; }
        public decimal FTE { get; set; }
        public string LevelGrade { get; set; }
        public string LevelName { get; set; }
        public int HomeOfficeCode { get; set; }
        public string HomeOfficeName { get; set; }
        public string HomeOfficeAbbreviation { get; set; }
        public string ActiveStatus { get; set; }
        public int OperatingOfficeCode { get; set; }
        public string OperatingOfficeName { get; set; }
        public string OperatingOfficeAbbreviation { get; set; }
        public string InternetAddress { get; set; }
        public string MentorEcode { get; set; }
        public string MentorName { get; set; }
        public string PositionCode { get; set; }
        public string PositionName { get; set; }
        public string PositionGroupName { get; set; }
        public string ServiceLineCode { get; set; }
        public string ServiceLineName { get; set; }
        public string ServiceLineHierarchyCode { get; set; }
        public string ServiceLineHierarchyName { get; set; }
        public decimal BillCode { get; set; }
        public bool Status { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime HireDate { get; set; }
        public DateTime? TerminationDate { get; set; }
        public string Uri { get; set; }
        public string UriHash { get; set; }
        public string EmployeeType { get; set; }
        public string ProfileImageUrl { get; set; }
        public Guid? Id { get; set; }
        public int ClientCode { get; set; }
        public int CaseCode { get; set; }
        public string OldCaseCode { get; set; }
        public string CurrentLevelGrade { get; set; }
        public int Allocation { get; set; }
        public DateTime? EndDate { get; set; }
        public Guid PipelineId { get; set; }
        public short InvestmentCode { get; set; }
        public string InvestmentName { get; set; }
        public string CaseRoleCode { get; set; }
        public string CaseRoleName { get; set; }
        public string Notes { get; set; }
        public DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
        public string CommitmentTypeCode { get; set; }
        public string CommitmentTypeName { get; set; }
        public string Role { get; set; }
        public string TrainingName { get; set; }
        public string EmployeeStatus { get; set; }
        public string BusinessProcessEvent { get; set; }
        public string BusinessProcessReason { get; set; }
        public string BusinessProcessType { get; set; }
        public string BusinessProcessName { get; set; }
        public DateTime? CompletedDate { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        public DateTime? MostRecentCorrectionDate { get; set; }
        public DateTime? TerminationEffectiveDate { get; set; }
        public string TransactionStatus { get; set; }
        public decimal? BillCodeCurrent { get; set; }
        public decimal? BillCodeProposed { get; set; }
        public decimal? FteCurrent { get; set; }
        public decimal? FteProposed { get; set; }
        public short? HomeOfficeCodeCurrent { get; set; }
        public short? HomeOfficeCodeProposed { get; set; }
        public short? OperatingOfficeCodeCurrent { get; set; }
        public short? OperatingOfficeCodeProposed { get; set; }
        public string PDGradeCurrent { get; set; }
        public string PDGradeProposed { get; set; }
        public string PositionNameCurrent { get; set; }
        public string PositionNameProposed { get; set; }
        public string PositionGroupNameCurrent { get; set; }
        public string PositionGroupNameProposed { get; set; }
        public string ServiceLineCodeCurrent { get; set; }
        public string ServiceLineCodeProposed { get; set; }
        public string ServiceLineNameCurrent { get; set; }
        public string ServiceLineNameProposed { get; set; }
        public DateTime? TransitionStartDate { get; set; }
        public DateTime? TransitionEndDate { get; set; }
        public string CostCentreIdCurrent { get; set; }
        public string CostCentreIdProposed { get; set; }
        public bool? IsRescinded { get; set; }
        public bool? IsRescindProcessed { get; set; }
        public DateTime? RescindProcessedDate { get; set; }
        public string TargetLastUpdated { get; set; }
        public string Description { get; set; }
        public string SysCollection { get; set; }
        public string Title { get; set; }
    }
}
