export const environment = {
  name: 'local',
  production: false,
  settings: {
    'showWidgetIcon': true,
    'ocelotApiGatewayBaseUrl': '',
    'staffingAuthenticationApiBaseUrl': '',
    'resourcesApiBaseUrl': '',
    'pegC2COpportunityDetailsUrl':'',
    'launchDarklyClientId': '',
    'projectsPageSize': 60,
    'resourcesPerPage': 50,
    "itemSizeForVirtualScroll": 50,
    'scrollDistance': 3,
    'NumberOfWeeksForCasePlanningBoard': 6,
    'googleAnalyticsJqueryUrl': '',
    'googleAnalyticsJsUrl': '',
    'googleAnalyticsProfileUrl': '',
    'tableauStaffingAllocationReportUrl': '',
    'tableauStaffingAllocationsMonthlyReportUrl':'',
    'tableauStaffingInsightsReportUrl':'',
    'tableauHistoricalAllocationsForPromotionsUrl':'',
    'tableauAvailabilityReportUrl': '',
    'tableauDailyDeploymentDetailsReportUrl': '',
    'tableauIndividualResourceDetailsReportUrl': '',
    'tableauWeeklyDeploymentSummaryReportUrl': '',
    'tableauMonthlyDeploymentReportUrl':'',
    'tableauFTEUtilizationReportUrl':'',
    'tableauFTEUtilizationIndividualReportUrl':'',
    'tableauCapacityPlanningCaseViewReportUrl':'',
    'tableauRingfenceStaffingReportUrl': '',
    'tableauOverAllocatedAuditReportUrl': '',
    'tableauAllocatedWhileOnLOAAuditReportUrl': '',
    'tableauCaseUpdatesAuditReportUrl': '',
    'tableauPriceRealizationUrl':'',
    'tableauMonthlyPracticeAreaStaffingUrl': '',
    'tableauCommitmentDetailsUrl': '',
    'irisProfileBaseUrl':'',
    'clearLocalStorage': 'false',
    'siteUnderMaintainance': 'false',
    'environmentUrl': '',
    'tableauTimeInLaneReportUrl':'',
    'tableauPracticeStaffingCaseServedReportUrl':'',
    'tableauAffiliateTimeInPracticeReportUrl':'',
    'tableauCaseEconomicsReportUrl':'',
    'tableauCaseEconomicsNonBillableReportUrl':'',
    'tableauWhoWorkedWithWhomReportUrl':'',
    'tableauWhoSMAPAllocationsReportUrl':'',
    'tableauCaseExperienceReportUrl':'',
    'tableauGlobalCapacitySummaryUrl':'',
    'tableauGlobalClientFacingHeadCountReportUrl': '',
    'globalStaffingSupportMailbox': '',
    'externalNavParameters': '',
    'instrumentationKey': '',
    "monthCloseDay":21,
    "hideBulkUpdate": true,
    "monthCloseOffset": {
      "January": 1,
      "February": 1,
      "March": 1,
      "April": 1,
      "May": 1,
      "June": 1,
      "July": 1,
      "August": 1,
      "September": 1,
      "October": 1,
      "November": 1,
      "December": 1
  },
  eCodesWithImpersonationAccess: []
  },
  imageExtensions: ['.png', '.jpeg'],
  azureActiveDirectorySettings:{
    enableAAD: false,
    staffing_automation_testing_username: "",
    clientId:"",
    tenantId:"",
    redirectUri:""
  },
  resourcesApiConfig:{
    subscriptionKey:"",
    version: "",
    token: ""
  }
};
