using Iris.API.Contracts.Helpers;
using Iris.API.Contracts.Helpers.RepositoryInterfaces;
using Iris.API.Contracts.RepositoryInterfaces;
using Iris.API.Contracts.Services;
using Iris.API.Core.Helpers;
using Iris.API.Core.Repository;
using Iris.API.Core.Services;
using Iris.API.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Tokens;
using Microsoft.OpenApi.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;

namespace Iris.API.Extensions
{
    public static class ServiceExtensions
    {
        public static IServiceCollection RegisterAppServices(this IServiceCollection services)
        {
            services.AddScoped<IDapperContext, DapperContext>();

            #region CORS

            services.AddCors(o => o.AddPolicy("CorsPolicy", builder =>
            {
                builder.AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .SetPreflightMaxAge(TimeSpan.FromSeconds(7200));
            }));

            #endregion

            #region BaseRepository

            services.AddScoped<IBaseRepository<EmployeeWorkHistory>, BaseRepository<EmployeeWorkHistory>>();
            services.AddScoped<IBaseRepository<EmployeeSchoolHistory>, BaseRepository<EmployeeSchoolHistory>>();
            services.AddScoped<IBaseRepository<PracticeArea>, BaseRepository<PracticeArea>>();

            #endregion

            #region Repository

            services.AddScoped<IPracticeAreaRepository, PracticeAreaRepository>();

            #endregion

            #region Services
            services.AddScoped<IPracticeAreaService, PracticeAreaService>();
            services.AddScoped<IEmployeeWorkAndSchoolHistoryService, EmployeeWorkAndSchoolHistoryService>();

            #endregion

            #region Api Services

            services.AddTransient<HttpClientAuthorizationDelegatingHandler>();
            services.AddHttpContextAccessor();

            services.AddHttpClient<IirisApiClient, IrisApiClient>()
                .AddHttpMessageHandler<HttpClientAuthorizationDelegatingHandler>();
            #endregion

            #region JWT Authentication

            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        ValidateLifetime = true,
                        ValidateIssuerSigningKey = true,
                        ValidateAudience = true,
                        ValidateIssuer = true,

                        ValidIssuer = "Staffing Authentication API",
                        ValidAudience = "APIs accessed by Staffing App",
                        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8
                            .GetBytes(Environment.GetEnvironmentVariable("staffing_secretKey")))
                    };
                });

            #endregion

            #region Swagger

            services.AddSwaggerGen(options =>
            {
                // The generated Swagger JSON file will have these properties.
                options.SwaggerDoc("v1", new OpenApiInfo
                {
                    Title = "Iris API",
                    Version = "v1",
                    Description = "Get employee information"
                });

                options.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
                {
                    In = ParameterLocation.Header,
                    Description = "JWT Authorization header using the Bearer scheme. \r\n\r\n Enter 'Bearer' [space] and then your token in the text input below.\r\n\r\nExample: \"Bearer 12345abcdef\"",
                    Name = "Authorization",
                    Type = SecuritySchemeType.ApiKey,
                    Scheme = "Bearer"
                });

                options.AddSecurityRequirement(new OpenApiSecurityRequirement()
                 {
                    {
                        new OpenApiSecurityScheme
                        {
                            Reference = new OpenApiReference
                            {
                                Type = ReferenceType.SecurityScheme,
                                Id = "Bearer"
                            },
                            Scheme = "oauth2",
                            Name = "Bearer",
                            In = ParameterLocation.Header,
                        },
                        new List<string>()
                     }
                  });

                //Locate the XML file being generated by ASP.NET
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.XML";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

                //Tell swagger to use XML comments
                options.IncludeXmlComments(xmlPath);
            });

            #endregion

            return services;
        }
    }
}